from __future__ import annotations
import asyncio
from typing import Optional
import httpx
from app.config import settings


async def send_email(
    to: str,
    subject: str,
    html: str,
    from_email: Optional[str] = None,
    api_key: Optional[str] = None,
) -> bool:
    """Send email via Resend API. Returns True on success."""
    key = api_key or settings.RESEND_API_KEY
    sender = from_email or settings.FROM_EMAIL
    if not key:
        return False

    payload = {"from": sender, "to": [to], "subject": subject, "html": html}
    for attempt in range(3):
        try:
            async with httpx.AsyncClient(timeout=8.0) as client:
                r = await client.post(
                    "https://api.resend.com/emails",
                    headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
                    json=payload,
                )
                r.raise_for_status()
                return True
        except httpx.HTTPStatusError:
            return False
        except httpx.RequestError:
            if attempt == 2:
                return False
            await asyncio.sleep(0.5)
    return False


def payment_link_html(checkout_url: str, product_name: str = "", amount: str = "") -> str:
    return f"""
<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;max-width:600px;margin:auto;padding:24px;">
  <h2>Your Payment Link</h2>
  {"<p>Product: <strong>" + product_name + "</strong></p>" if product_name else ""}
  {"<p>Amount: <strong>" + amount + "</strong></p>" if amount else ""}
  <p>
    <a href="{checkout_url}"
       style="background:#4f46e5;color:#fff;padding:14px 28px;border-radius:8px;
              text-decoration:none;font-weight:bold;display:inline-block;">
      Complete Your Purchase
    </a>
  </p>
  <p style="color:#666;font-size:12px;">
    This link was generated by your AI sales assistant. If you did not request this, please ignore.
  </p>
</body>
</html>
"""
