"""
Outbound notification helpers: email (Resend) and SMS (Twilio REST).

Both functions are async, fire-and-forget safe, and return bool success.
No SDK dependencies — raw httpx only to keep the service lightweight.
"""
from __future__ import annotations

import asyncio
import logging
from typing import Optional

import httpx

logger = logging.getLogger(__name__)

_TIMEOUT = httpx.Timeout(8.0, connect=3.0)


# ── Email via Resend ──────────────────────────────────────────────────────────


async def send_email(
    to: str,
    subject: str,
    html: str,
    api_key: str,
    from_email: str = "orders@sureshotbooks.com",
) -> bool:
    """
    Send a transactional email via Resend API.
    Returns True on success, False on any failure (never raises).

    Example:
        sent = await send_email(
            to="customer@example.com",
            subject="Your payment link",
            html="<a href='...'>Pay Now</a>",
            api_key=agent_config.resend_api_key,
        )
    """
    if not api_key:
        logger.warning("send_email: no Resend API key configured")
        return False

    payload = {
        "from": from_email,
        "to": [to],
        "subject": subject,
        "html": html,
    }

    for attempt in range(3):
        try:
            async with httpx.AsyncClient(timeout=_TIMEOUT) as client:
                r = await client.post(
                    "https://api.resend.com/emails",
                    headers={
                        "Authorization": f"Bearer {api_key}",
                        "Content-Type": "application/json",
                    },
                    json=payload,
                )
                r.raise_for_status()
                logger.info("Email sent to %s via Resend", to)
                return True
        except httpx.HTTPStatusError as exc:
            logger.error("Resend HTTP error %s: %s", exc.response.status_code, exc.response.text)
            return False
        except httpx.RequestError as exc:
            if attempt == 2:
                logger.error("Resend connection failed after 3 attempts: %s", exc)
                return False
            await asyncio.sleep(0.5 * (attempt + 1))

    return False


def payment_link_html(
    checkout_url: str,
    product_name: str = "",
    amount: str = "",
    facility_note: str = "",
) -> str:
    """Minimal HTML email body for payment link delivery."""
    product_line = f"<p>Item: <strong>{product_name}</strong></p>" if product_name else ""
    amount_line = f"<p>Amount: <strong>{amount}</strong></p>" if amount else ""
    facility_line = (
        f"<p style='color:#555;'>Shipping to: {facility_note}</p>" if facility_note else ""
    )
    return f"""<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;max-width:600px;margin:auto;padding:24px;">
  <h2 style="color:#1a1a2e;">Your Payment Link</h2>
  {product_line}
  {amount_line}
  {facility_line}
  <p style="margin:24px 0;">
    <a href="{checkout_url}"
       style="background:#4f46e5;color:#fff;padding:14px 28px;border-radius:8px;
              text-decoration:none;font-weight:bold;display:inline-block;">
      Complete Your Purchase
    </a>
  </p>
  <p style="color:#999;font-size:12px;">
    Generated by your AI sales assistant. If you did not request this, please ignore.
  </p>
</body>
</html>"""


# ── SMS via Twilio REST ───────────────────────────────────────────────────────


async def send_sms(
    to: str,
    body: str,
    from_number: str,
    account_sid: str,
    auth_token: str,
) -> bool:
    """
    Send an SMS via the Twilio REST API (no SDK).
    Returns True on success, False on any failure (never raises).

    Example:
        sent = await send_sms(
            to="+15551234567",
            body="Your payment link: https://...",
            from_number=settings.TWILIO_PHONE_NUMBER,
            account_sid=settings.TWILIO_ACCOUNT_SID,
            auth_token=settings.TWILIO_AUTH_TOKEN,
        )
    """
    if not all([account_sid, auth_token, from_number]):
        logger.warning("send_sms: Twilio credentials not fully configured")
        return False

    url = f"https://api.twilio.com/2010-04-01/Accounts/{account_sid}/Messages.json"

    try:
        async with httpx.AsyncClient(timeout=_TIMEOUT) as client:
            r = await client.post(
                url,
                auth=(account_sid, auth_token),
                data={"To": to, "From": from_number, "Body": body[:1600]},
            )
            r.raise_for_status()
            sid = r.json().get("sid", "unknown")
            logger.info("SMS sent to %s via Twilio (sid=%s)", to, sid)
            return True
    except httpx.HTTPStatusError as exc:
        logger.error("Twilio HTTP error %s: %s", exc.response.status_code, exc.response.text)
        return False
    except httpx.RequestError as exc:
        logger.error("Twilio connection failed: %s", exc)
        return False
