import { createHash, randomUUID } from "node:crypto";
import type { CallSession } from "../types/order.js";
import { ensureSessionMemory } from "./sessionMemory.js";
import { sendSupportCaseEmail } from "../infra/supportEmailClient.js";
import { notifySupportCaseWebhook } from "../infra/supportWebhookClient.js";

export interface CreateSupportCaseRequest {
  session: CallSession;
  /**
   * Idempotency token generated by ActionGateway / orchestrator — NEVER by the LLM.
   * Same `requestId` + matching payload fingerprint returns the existing case; a
   * conflicting payload for the same `requestId` returns `idempotency_conflict`.
   */
  requestId?: string;
  callId?: string;
  turnId?: string;
  reasonCode?: string;
  reason: string;
  issueSummary?: string;
  customerName?: string;
  callbackEmail?: string;
  orderNumber?: string;
  /** Opaque disclosure-safe order reference (e.g. session order number). */
  orderReferenceId?: string;
  checkoutPlanId?: string;
}

interface StoredCaseRecord {
  caseId: string;
  reason: string;
  createdAt: number;
  issueSummary?: string;
  verificationLevel: "verified" | "unverified";
  emailSent?: boolean;
  webhookNotified?: boolean;
  notificationAttemptedAt?: number;
  /** Idempotency metadata — invisible to the LLM. */
  requestId?: string;
  payloadFingerprint?: string;
  /**
   * Concurrent-notify guard. When set, an in-flight caller is already awaiting
   * the email/webhook Promises for this case — subsequent callers with the same
   * requestId piggy-back on that promise instead of re-sending.
   */
  notificationPromise?: Promise<{ emailSent: boolean; webhookNotified: boolean }>;
}

export type CreateSupportCaseResult =
  | {
      ok: true;
      caseId: string;
      emailSent: boolean;
      webhookNotified: boolean;
      reused?: boolean;
    }
  | { ok: false; error: string; caseId?: string };

function stableFingerprint(request: CreateSupportCaseRequest): string {
  const material = JSON.stringify({
    reason: request.reason?.trim(),
    reasonCode: request.reasonCode ?? null,
    issueSummary: request.issueSummary ?? null,
    orderNumber: request.orderNumber ?? request.orderReferenceId ?? null,
    checkoutPlanId: request.checkoutPlanId ?? null,
    callId: request.callId ?? request.session.callSid,
  });
  return createHash("sha256").update(material).digest("hex").slice(0, 24);
}

/**
 * Persist exactly one support case per requestId. Retries with the same
 * requestId return the existing caseId; conflicting payloads fail closed.
 */
export async function createCase(
  request: CreateSupportCaseRequest,
): Promise<CreateSupportCaseResult> {
  const { session, reason } = request;
  if (!reason.trim()) return { ok: false, error: "Support case reason is required." };
  const memory = ensureSessionMemory(session);
  const cases = (memory.supportCases ??= []) as StoredCaseRecord[];
  const fingerprint = stableFingerprint(request);

  // Idempotency: same requestId → reuse or fail on conflict.
  if (request.requestId) {
    const priorByRequest = cases.find((entry) => entry.requestId === request.requestId);
    if (priorByRequest) {
      if (
        priorByRequest.payloadFingerprint &&
        priorByRequest.payloadFingerprint !== fingerprint
      ) {
        return {
          ok: false,
          error: "idempotency_conflict",
          caseId: priorByRequest.caseId,
        };
      }
      // Piggy-back on an in-flight notify so Promise.all does not fan out.
      if (priorByRequest.notificationPromise) {
        const settled = await priorByRequest.notificationPromise;
        return {
          ok: true,
          caseId: priorByRequest.caseId,
          emailSent: settled.emailSent,
          webhookNotified: settled.webhookNotified,
          reused: true,
        };
      }
      // Optional notify retry — only when the prior attempt did not confirm delivery.
      if (!priorByRequest.emailSent || !priorByRequest.webhookNotified) {
        const retry = (async () => {
          const [email, webhookNotified] = await Promise.all([
            !priorByRequest.emailSent
              ? sendSupportCaseEmail({
                  customerName: request.customerName ?? "",
                  callbackEmail: request.callbackEmail ?? "",
                  callerPhone: session.from ?? "",
                  isVerifiedCaller: session.isVerifiedCaller === true,
                  orderNumber: request.orderNumber,
                  requestedInfo: "support request",
                  escalationReason: reason,
                  issueDescription: request.issueSummary ?? reason,
                  recommendedAction: "Follow up with the caller.",
                })
              : Promise.resolve({ ok: priorByRequest.emailSent === true }),
            !priorByRequest.webhookNotified
              ? notifySupportCaseWebhook({
                  caseId: priorByRequest.caseId,
                  callSid: session.callSid,
                  reason,
                })
              : Promise.resolve(priorByRequest.webhookNotified === true),
          ]);
          priorByRequest.emailSent = email.ok || priorByRequest.emailSent === true;
          priorByRequest.webhookNotified =
            webhookNotified || priorByRequest.webhookNotified === true;
          priorByRequest.notificationAttemptedAt = Date.now();
          return {
            emailSent: priorByRequest.emailSent === true,
            webhookNotified: priorByRequest.webhookNotified === true,
          };
        })();
        priorByRequest.notificationPromise = retry;
        try {
          await retry;
        } finally {
          priorByRequest.notificationPromise = undefined;
        }
      }
      return {
        ok: true,
        caseId: priorByRequest.caseId,
        emailSent: priorByRequest.emailSent === true,
        webhookNotified: priorByRequest.webhookNotified === true,
        reused: true,
      };
    }
  } else {
    // No requestId — de-dupe on payload fingerprint from the same call to keep
    // pre-idempotency callers safe. Cases with distinct fingerprints always create.
    const priorByFingerprint = cases.find(
      (entry) => entry.payloadFingerprint === fingerprint && !entry.requestId,
    );
    if (priorByFingerprint) {
      return {
        ok: true,
        caseId: priorByFingerprint.caseId,
        emailSent: priorByFingerprint.emailSent === true,
        webhookNotified: priorByFingerprint.webhookNotified === true,
        reused: true,
      };
    }
  }

  const caseId = `HUM-${session.callSid.slice(0, 8)}-${randomUUID().slice(0, 8)}`;
  const record: StoredCaseRecord = {
    caseId,
    reason,
    createdAt: Date.now(),
    issueSummary: request.issueSummary,
    verificationLevel: session.isVerifiedCaller ? "verified" : "unverified",
    requestId: request.requestId,
    payloadFingerprint: fingerprint,
  };
  cases.push(record);
  memory.sentimentShieldActive = true;
  memory.humanEscalationTriggered = true;

  const notify = (async () => {
    const [email, webhookNotified] = await Promise.all([
      sendSupportCaseEmail({
        customerName: request.customerName ?? "",
        callbackEmail: request.callbackEmail ?? "",
        callerPhone: session.from ?? "",
        isVerifiedCaller: session.isVerifiedCaller === true,
        orderNumber: request.orderNumber,
        requestedInfo: "support request",
        escalationReason: reason,
        issueDescription: request.issueSummary ?? reason,
        recommendedAction: "Follow up with the caller.",
      }),
      notifySupportCaseWebhook({ caseId, callSid: session.callSid, reason }),
    ]);
    record.emailSent = email.ok;
    record.webhookNotified = webhookNotified;
    record.notificationAttemptedAt = Date.now();
    return { emailSent: email.ok, webhookNotified };
  })();
  record.notificationPromise = notify;
  try {
    const settled = await notify;
    return {
      ok: true,
      caseId,
      emailSent: settled.emailSent,
      webhookNotified: settled.webhookNotified,
    };
  } finally {
    record.notificationPromise = undefined;
  }
}

/** Compatibility facade for local-only callers. */
export function createSupportCase(
  session: CallSession,
  reason: string,
): { ok: true; caseId: string } {
  const memory = ensureSessionMemory(session);
  const caseId = `HUM-${session.callSid.slice(0, 8)}-${randomUUID().slice(0, 8)}`;
  (memory.supportCases ??= []).push({
    caseId,
    reason,
    createdAt: Date.now(),
    verificationLevel: session.isVerifiedCaller ? "verified" : "unverified",
  });
  memory.sentimentShieldActive = true;
  memory.humanEscalationTriggered = true;
  return { ok: true, caseId };
}

export const SupportCaseService = { createCase, createSupportCase } as const;
